### ISSUE TITLE
cannot import name 'FinalEvalRewardEnv'

### ISSUE THREAD

**Issue by wangxiaochun520** [opendilab/DI-sheep#5]
while run "from ding.envs import create_env_manager, DingEnvWrapper, FinalEvalRewardEnv ",”cannot import name 'FinalEvalRewardEnv“error has occurred，look for codebase ,don't find about FinalEvalRewardEnv  content.

**Comment by PaParaZz1** [comment]
Sorry about this bug. It is because the API change of DI-engine in v0.4.5. We will fix this problem in this weekend.

**Comment by PaParaZz1** [comment]
I have fixed this problem, you can try now.
